name: Test & Release & Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #device: [d2bravo, d2bravo_titanium, fenix3, fenix3_hr, fr230, fr235, fr735xt, vivoactive4]
        device: [fr235]
    steps:
      - uses: actions/checkout@v4
      - name: Test on device ${{ matrix.device }}
        id: run_tests
        uses: adamjakab/action-connectiq-builder@v1
        with:
          operation: TEST
          device: ${{ matrix.device }}
          certificate: ${{ secrets.CONNECTIQ_DEVELOPER_KEY_BASE64}}
  release:
    needs: test
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          #name: ${{ github.ref_name }}
          #artifacts: "bin/iHIIT.iq"
          generateReleaseNotes: true
          prerelease: true
      - name: Package App
        id: package_app
        uses: adamjakab/action-connectiq-builder@v1
        with:
          operation: PACKAGE
          certificate: ${{ secrets.CONNECTIQ_DEVELOPER_KEY_BASE64}}
          package_name: iHIIT_${{ github.ref_name }}.iq
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/iHIIT_${{ github.ref_name }}.iq
          asset_name: iHIIT_${{ github.ref_name }}.iq
          asset_content_type: application/gzip

