name: Test & Release & Deploy

# on:
#   push:
#     tags:
#       - "v*"
on:
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test application
        id: run_tests
        uses: adamjakab/action-connectiq-builder@v1
        with:
          device: fr235
